import os

from backend.heart_alert_vars import (
    EMERGENCY_EMAIL,
    ESCALATION_MINUTES,
    HIGH_BPM,
    LOW_BPM,
    SELF_EMAIL,
)


HEART_ALERT_LOW_BPM = int(os.getenv("HEART_ALERT_LOW_BPM", str(LOW_BPM)))
HEART_ALERT_HIGH_BPM = int(os.getenv("HEART_ALERT_HIGH_BPM", str(HIGH_BPM)))
HEART_ALERT_ESCALATION_MINUTES = int(os.getenv("HEART_ALERT_ESCALATION_MINUTES", str(ESCALATION_MINUTES)))

SMTP_HOST = os.getenv("HEART_ALERT_SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("HEART_ALERT_SMTP_PORT", "587"))
SMTP_USERNAME = os.getenv("HEART_ALERT_SMTP_USERNAME", "")
SMTP_PASSWORD = os.getenv("HEART_ALERT_SMTP_PASSWORD", "")
SMTP_FROM_EMAIL = os.getenv("HEART_ALERT_FROM_EMAIL", SMTP_USERNAME)

DEFAULT_SELF_EMAIL = os.getenv("HEART_ALERT_SELF_EMAIL", SELF_EMAIL)
DEFAULT_EMERGENCY_EMAIL = os.getenv("HEART_ALERT_EMERGENCY_EMAIL", EMERGENCY_EMAIL)
